export type QuizType =
  | "Technology"
  | "Academia"
  | "Engineering"
  | "Law"
  | "Economics"
  | "General"
  | "Science"
  | "History"
  | "Politics"

export type DifficultyLevel = "Easy" | "Intermediate" | "Hard"

export interface Question {
  question: string
  options: string[]
  correctAnswer: number
  category: QuizType
  difficulty: DifficultyLevel
}

export const QUIZ_DATA: Question[] = [
  // Technology - Easy (10 questions)
  {
    question: "What does HTML stand for?",
    options: [
      "Hyper Text Markup Language",
      "High Tech Modern Language",
      "Home Tool Markup Language",
      "Hyperlinks and Text Markup Language",
    ],
    correctAnswer: 0,
    category: "Technology",
    difficulty: "Easy",
  },
  {
    question: "Which company developed the iPhone?",
    options: ["Samsung", "Apple", "Google", "Microsoft"],
    correctAnswer: 1,
    category: "Technology",
    difficulty: "Easy",
  },
  {
    question: "What does CPU stand for?",
    options: [
      "Central Processing Unit",
      "Computer Personal Unit",
      "Central Program Utility",
      "Computer Processing Unit",
    ],
    correctAnswer: 0,
    category: "Technology",
    difficulty: "Easy",
  },
  {
    question: "What does USB stand for?",
    options: ["Universal Serial Bus", "Universal System Board", "United Serial Bus", "Universal Service Bus"],
    correctAnswer: 0,
    category: "Technology",
    difficulty: "Easy",
  },
  {
    question: "Which of these is a web browser?",
    options: ["Python", "Chrome", "Windows", "Excel"],
    correctAnswer: 1,
    category: "Technology",
    difficulty: "Easy",
  },
  {
    question: "What does WWW stand for?",
    options: ["World Wide Web", "World Wide Wait", "Web Wide World", "World Web Wide"],
    correctAnswer: 0,
    category: "Technology",
    difficulty: "Easy",
  },
  {
    question: "What is the most popular programming language for web development?",
    options: ["Python", "JavaScript", "C++", "Ruby"],
    correctAnswer: 1,
    category: "Technology",
    difficulty: "Easy",
  },
  {
    question: "What does RAM stand for?",
    options: ["Random Access Memory", "Read Access Memory", "Run Access Memory", "Real Access Memory"],
    correctAnswer: 0,
    category: "Technology",
    difficulty: "Easy",
  },
  {
    question: "Which company created the Android operating system?",
    options: ["Apple", "Microsoft", "Google", "Samsung"],
    correctAnswer: 2,
    category: "Technology",
    difficulty: "Easy",
  },
  {
    question: "What is the main function of an operating system?",
    options: ["Browse the internet", "Manage computer hardware and software", "Create documents", "Play games"],
    correctAnswer: 1,
    category: "Technology",
    difficulty: "Easy",
  },

  // Technology - Intermediate (10 questions)
  {
    question: "Which programming language is known as the 'language of the web'?",
    options: ["Python", "JavaScript", "Java", "C++"],
    correctAnswer: 1,
    category: "Technology",
    difficulty: "Intermediate",
  },
  {
    question: "What is the time complexity of binary search?",
    options: ["O(n)", "O(log n)", "O(n²)", "O(1)"],
    correctAnswer: 1,
    category: "Technology",
    difficulty: "Intermediate",
  },
  {
    question: "What does API stand for?",
    options: [
      "Application Programming Interface",
      "Advanced Programming Interface",
      "Application Process Integration",
      "Advanced Process Interface",
    ],
    correctAnswer: 0,
    category: "Technology",
    difficulty: "Intermediate",
  },
  {
    question: "Which data structure uses LIFO (Last In First Out)?",
    options: ["Queue", "Stack", "Array", "Tree"],
    correctAnswer: 1,
    category: "Technology",
    difficulty: "Intermediate",
  },
  {
    question: "What is the purpose of Git?",
    options: ["Database management", "Version control", "Web hosting", "Image editing"],
    correctAnswer: 1,
    category: "Technology",
    difficulty: "Intermediate",
  },
  {
    question: "Which protocol is used for secure web communication?",
    options: ["HTTP", "FTP", "HTTPS", "SMTP"],
    correctAnswer: 2,
    category: "Technology",
    difficulty: "Intermediate",
  },
  {
    question: "What does SQL stand for?",
    options: ["Structured Query Language", "Standard Query Language", "Simple Query Language", "System Query Language"],
    correctAnswer: 0,
    category: "Technology",
    difficulty: "Intermediate",
  },
  {
    question: "Which is NOT a JavaScript framework?",
    options: ["React", "Angular", "Vue", "Django"],
    correctAnswer: 3,
    category: "Technology",
    difficulty: "Intermediate",
  },
  {
    question: "What is the default port for HTTP?",
    options: ["21", "80", "443", "8080"],
    correctAnswer: 1,
    category: "Technology",
    difficulty: "Intermediate",
  },
  {
    question: "What does CSS stand for?",
    options: ["Cascading Style Sheets", "Computer Style Sheets", "Creative Style Sheets", "Colorful Style Sheets"],
    correctAnswer: 0,
    category: "Technology",
    difficulty: "Intermediate",
  },

  // Technology - Hard (10 questions)
  {
    question: "What consensus algorithm does Bitcoin use?",
    options: ["Proof of Stake", "Proof of Work", "Delegated Proof of Stake", "Proof of Authority"],
    correctAnswer: 1,
    category: "Technology",
    difficulty: "Hard",
  },
  {
    question: "Which design pattern ensures a class has only one instance?",
    options: ["Factory Pattern", "Observer Pattern", "Singleton Pattern", "Strategy Pattern"],
    correctAnswer: 2,
    category: "Technology",
    difficulty: "Hard",
  },
  {
    question: "What is the CAP theorem in distributed systems?",
    options: [
      "Consistency, Availability, Partition tolerance",
      "Concurrency, Authentication, Performance",
      "Cache, API, Protocol",
      "Compute, Access, Processing",
    ],
    correctAnswer: 0,
    category: "Technology",
    difficulty: "Hard",
  },
  {
    question: "Which sorting algorithm has the best average time complexity?",
    options: ["Bubble Sort", "Quick Sort", "Insertion Sort", "Selection Sort"],
    correctAnswer: 1,
    category: "Technology",
    difficulty: "Hard",
  },
  {
    question: "What is the difference between TCP and UDP?",
    options: [
      "TCP is faster than UDP",
      "TCP is connection-oriented, UDP is connectionless",
      "UDP is more reliable than TCP",
      "They are the same",
    ],
    correctAnswer: 1,
    category: "Technology",
    difficulty: "Hard",
  },
  {
    question: "What does ACID stand for in database transactions?",
    options: [
      "Atomicity, Consistency, Isolation, Durability",
      "Access, Control, Identity, Data",
      "Authentication, Connection, Integration, Distribution",
      "Application, Cache, Index, Database",
    ],
    correctAnswer: 0,
    category: "Technology",
    difficulty: "Hard",
  },
  {
    question: "Which algorithm is used for public key cryptography?",
    options: ["AES", "DES", "RSA", "MD5"],
    correctAnswer: 2,
    category: "Technology",
    difficulty: "Hard",
  },
  {
    question: "What is the purpose of a Virtual DOM in React?",
    options: ["Store user data", "Optimize rendering performance", "Handle routing", "Manage state"],
    correctAnswer: 1,
    category: "Technology",
    difficulty: "Hard",
  },
  {
    question: "What is the time complexity of the best comparison-based sorting algorithm?",
    options: ["O(n)", "O(n log n)", "O(n²)", "O(log n)"],
    correctAnswer: 1,
    category: "Technology",
    difficulty: "Hard",
  },
  {
    question: "Which layer of the OSI model handles routing?",
    options: ["Physical Layer", "Data Link Layer", "Network Layer", "Transport Layer"],
    correctAnswer: 2,
    category: "Technology",
    difficulty: "Hard",
  },

  // Science - Easy (10 questions)
  {
    question: "What is the chemical symbol for water?",
    options: ["H2O", "CO2", "O2", "HO"],
    correctAnswer: 0,
    category: "Science",
    difficulty: "Easy",
  },
  {
    question: "How many planets are in our solar system?",
    options: ["7", "8", "9", "10"],
    correctAnswer: 1,
    category: "Science",
    difficulty: "Easy",
  },
  {
    question: "What gas do plants absorb from the atmosphere?",
    options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"],
    correctAnswer: 2,
    category: "Science",
    difficulty: "Easy",
  },
  {
    question: "What is the largest organ in the human body?",
    options: ["Heart", "Liver", "Brain", "Skin"],
    correctAnswer: 3,
    category: "Science",
    difficulty: "Easy",
  },
  {
    question: "At what temperature does water boil (in Celsius)?",
    options: ["50°C", "75°C", "100°C", "125°C"],
    correctAnswer: 2,
    category: "Science",
    difficulty: "Easy",
  },
  {
    question: "What force keeps us on the ground?",
    options: ["Magnetism", "Electricity", "Gravity", "Friction"],
    correctAnswer: 2,
    category: "Science",
    difficulty: "Easy",
  },
  {
    question: "How many bones are in the adult human body?",
    options: ["186", "206", "226", "246"],
    correctAnswer: 1,
    category: "Science",
    difficulty: "Easy",
  },
  {
    question: "What is the center of an atom called?",
    options: ["Electron", "Proton", "Nucleus", "Neutron"],
    correctAnswer: 2,
    category: "Science",
    difficulty: "Easy",
  },
  {
    question: "Which planet is closest to the Sun?",
    options: ["Venus", "Earth", "Mercury", "Mars"],
    correctAnswer: 2,
    category: "Science",
    difficulty: "Easy",
  },
  {
    question: "What is the chemical symbol for gold?",
    options: ["Go", "Gd", "Au", "Ag"],
    correctAnswer: 2,
    category: "Science",
    difficulty: "Easy",
  },

  // Science - Intermediate (10 questions)
  {
    question: "What is the speed of light in vacuum?",
    options: ["300,000 km/s", "150,000 km/s", "450,000 km/s", "600,000 km/s"],
    correctAnswer: 0,
    category: "Science",
    difficulty: "Intermediate",
  },
  {
    question: "What is the powerhouse of the cell?",
    options: ["Nucleus", "Ribosome", "Mitochondria", "Chloroplast"],
    correctAnswer: 2,
    category: "Science",
    difficulty: "Intermediate",
  },
  {
    question: "What type of bond involves the sharing of electron pairs?",
    options: ["Ionic bond", "Covalent bond", "Metallic bond", "Hydrogen bond"],
    correctAnswer: 1,
    category: "Science",
    difficulty: "Intermediate",
  },
  {
    question: "What is the pH of pure water?",
    options: ["5", "7", "9", "11"],
    correctAnswer: 1,
    category: "Science",
    difficulty: "Intermediate",
  },
  {
    question: "Which blood type is considered the universal donor?",
    options: ["A", "B", "AB", "O"],
    correctAnswer: 3,
    category: "Science",
    difficulty: "Intermediate",
  },
  {
    question: "What is Newton's second law of motion?",
    options: ["F = ma", "E = mc²", "V = IR", "PV = nRT"],
    correctAnswer: 0,
    category: "Science",
    difficulty: "Intermediate",
  },
  {
    question: "How many chromosomes do humans have?",
    options: ["23", "46", "48", "92"],
    correctAnswer: 1,
    category: "Science",
    difficulty: "Intermediate",
  },
  {
    question: "What is the most abundant gas in Earth's atmosphere?",
    options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Argon"],
    correctAnswer: 2,
    category: "Science",
    difficulty: "Intermediate",
  },
  {
    question: "What is the process by which plants make food?",
    options: ["Respiration", "Photosynthesis", "Transpiration", "Digestion"],
    correctAnswer: 1,
    category: "Science",
    difficulty: "Intermediate",
  },
  {
    question: "What is the smallest unit of life?",
    options: ["Atom", "Molecule", "Cell", "Tissue"],
    correctAnswer: 2,
    category: "Science",
    difficulty: "Intermediate",
  },

  // Science - Hard (10 questions)
  {
    question: "What is the Heisenberg Uncertainty Principle related to?",
    options: ["Chemical reactions", "Quantum mechanics", "Thermodynamics", "Relativity"],
    correctAnswer: 1,
    category: "Science",
    difficulty: "Hard",
  },
  {
    question: "What is Avogadro's number?",
    options: ["6.022 × 10²³", "3.14 × 10⁸", "1.602 × 10⁻¹⁹", "9.81 × 10¹"],
    correctAnswer: 0,
    category: "Science",
    difficulty: "Hard",
  },
  {
    question: "What particle is exchanged in electromagnetic interactions?",
    options: ["Gluon", "Photon", "W boson", "Graviton"],
    correctAnswer: 1,
    category: "Science",
    difficulty: "Hard",
  },
  {
    question: "What is the half-life of Carbon-14?",
    options: ["5,730 years", "10,000 years", "1,000 years", "50,000 years"],
    correctAnswer: 0,
    category: "Science",
    difficulty: "Hard",
  },
  {
    question: "What is the Schwarzschild radius?",
    options: [
      "Distance from Earth to Moon",
      "Radius of a black hole's event horizon",
      "Size of an atom",
      "Orbital radius of planets",
    ],
    correctAnswer: 1,
    category: "Science",
    difficulty: "Hard",
  },
  {
    question: "Which enzyme breaks down starch in the mouth?",
    options: ["Pepsin", "Amylase", "Lipase", "Trypsin"],
    correctAnswer: 1,
    category: "Science",
    difficulty: "Hard",
  },
  {
    question: "What is the principle behind MRI machines?",
    options: ["X-ray diffraction", "Nuclear magnetic resonance", "Ultrasound waves", "Radioactive decay"],
    correctAnswer: 1,
    category: "Science",
    difficulty: "Hard",
  },
  {
    question: "What is the name of the effect where time dilates near massive objects?",
    options: ["Doppler Effect", "Photoelectric Effect", "Gravitational Time Dilation", "Compton Effect"],
    correctAnswer: 2,
    category: "Science",
    difficulty: "Hard",
  },
  {
    question: "Which cycle describes carbon movement through the biosphere?",
    options: ["Krebs Cycle", "Calvin Cycle", "Carbon Cycle", "Nitrogen Cycle"],
    correctAnswer: 2,
    category: "Science",
    difficulty: "Hard",
  },
  {
    question: "What is the quantum mechanical model that describes electron orbitals?",
    options: ["Bohr Model", "Rutherford Model", "Schrödinger Model", "Dalton Model"],
    correctAnswer: 2,
    category: "Science",
    difficulty: "Hard",
  },

  // History - Easy (10 questions)
  {
    question: "In which year did World War II end?",
    options: ["1943", "1944", "1945", "1946"],
    correctAnswer: 2,
    category: "History",
    difficulty: "Easy",
  },
  {
    question: "Who was the first President of the United States?",
    options: ["Thomas Jefferson", "George Washington", "Abraham Lincoln", "John Adams"],
    correctAnswer: 1,
    category: "History",
    difficulty: "Easy",
  },
  {
    question: "Which ancient wonder is still standing today?",
    options: ["Hanging Gardens of Babylon", "Colossus of Rhodes", "Great Pyramid of Giza", "Lighthouse of Alexandria"],
    correctAnswer: 2,
    category: "History",
    difficulty: "Easy",
  },
  {
    question: "In which year did Christopher Columbus reach the Americas?",
    options: ["1492", "1500", "1520", "1450"],
    correctAnswer: 0,
    category: "History",
    difficulty: "Easy",
  },
  {
    question: "Who was known as the 'Maid of Orleans'?",
    options: ["Marie Antoinette", "Joan of Arc", "Catherine the Great", "Queen Victoria"],
    correctAnswer: 1,
    category: "History",
    difficulty: "Easy",
  },
  {
    question: "Which empire was ruled by Julius Caesar?",
    options: ["Greek Empire", "Roman Empire", "Persian Empire", "Egyptian Empire"],
    correctAnswer: 1,
    category: "History",
    difficulty: "Easy",
  },
  {
    question: "In which year did the Titanic sink?",
    options: ["1910", "1912", "1914", "1916"],
    correctAnswer: 1,
    category: "History",
    difficulty: "Easy",
  },
  {
    question: "Who painted the ceiling of the Sistine Chapel?",
    options: ["Leonardo da Vinci", "Raphael", "Michelangelo", "Donatello"],
    correctAnswer: 2,
    category: "History",
    difficulty: "Easy",
  },
  {
    question: "Which country gifted the Statue of Liberty to the USA?",
    options: ["England", "Spain", "France", "Italy"],
    correctAnswer: 2,
    category: "History",
    difficulty: "Easy",
  },
  {
    question: "Who invented the telephone?",
    options: ["Thomas Edison", "Alexander Graham Bell", "Nikola Tesla", "Benjamin Franklin"],
    correctAnswer: 1,
    category: "History",
    difficulty: "Easy",
  },

  // History - Intermediate (10 questions)
  {
    question: "The fall of the Berlin Wall occurred in which year?",
    options: ["1987", "1989", "1991", "1993"],
    correctAnswer: 1,
    category: "History",
    difficulty: "Intermediate",
  },
  {
    question: "Which document was signed in 1215 limiting the power of the English king?",
    options: ["Magna Carta", "Bill of Rights", "Declaration of Independence", "Constitution"],
    correctAnswer: 0,
    category: "History",
    difficulty: "Intermediate",
  },
  {
    question: "Who was the first emperor of Rome?",
    options: ["Julius Caesar", "Augustus", "Nero", "Caligula"],
    correctAnswer: 1,
    category: "History",
    difficulty: "Intermediate",
  },
  {
    question: "In which year did India gain independence?",
    options: ["1945", "1947", "1950", "1952"],
    correctAnswer: 1,
    category: "History",
    difficulty: "Intermediate",
  },
  {
    question: "What was the name of the ship that brought the Pilgrims to America?",
    options: ["Mayflower", "Santa Maria", "Victoria", "Endeavour"],
    correctAnswer: 0,
    category: "History",
    difficulty: "Intermediate",
  },
  {
    question: "Who was the first woman to win a Nobel Prize?",
    options: ["Marie Curie", "Mother Teresa", "Jane Addams", "Malala Yousafzai"],
    correctAnswer: 0,
    category: "History",
    difficulty: "Intermediate",
  },
  {
    question: "What was the Cold War?",
    options: ["A war fought in winter", "Tension between USA and USSR", "A war in Antarctica", "A nuclear war"],
    correctAnswer: 1,
    category: "History",
    difficulty: "Intermediate",
  },
  {
    question: "Which civilization built Machu Picchu?",
    options: ["Aztec", "Maya", "Inca", "Olmec"],
    correctAnswer: 2,
    category: "History",
    difficulty: "Intermediate",
  },
  {
    question: "In which year did the French Revolution begin?",
    options: ["1776", "1789", "1799", "1804"],
    correctAnswer: 1,
    category: "History",
    difficulty: "Intermediate",
  },
  {
    question: "Who was the leader of the Soviet Union during World War II?",
    options: ["Lenin", "Stalin", "Khrushchev", "Brezhnev"],
    correctAnswer: 1,
    category: "History",
    difficulty: "Intermediate",
  },

  // History - Hard (10 questions)
  {
    question: "The Treaty of Westphalia (1648) ended which war?",
    options: ["Hundred Years' War", "Thirty Years' War", "Seven Years' War", "War of Spanish Succession"],
    correctAnswer: 1,
    category: "History",
    difficulty: "Hard",
  },
  {
    question: "Which Byzantine emperor codified Roman law?",
    options: ["Constantine", "Justinian", "Theodosius", "Heraclius"],
    correctAnswer: 1,
    category: "History",
    difficulty: "Hard",
  },
  {
    question: "What year did the Battle of Hastings take place?",
    options: ["1066", "1215", "1492", "1588"],
    correctAnswer: 0,
    category: "History",
    difficulty: "Hard",
  },
  {
    question: "Who was the last Tsar of Russia?",
    options: ["Alexander II", "Alexander III", "Nicholas I", "Nicholas II"],
    correctAnswer: 3,
    category: "History",
    difficulty: "Hard",
  },
  {
    question: "Which empire was ruled by Suleiman the Magnificent?",
    options: ["Mughal Empire", "Ottoman Empire", "Safavid Empire", "Byzantine Empire"],
    correctAnswer: 1,
    category: "History",
    difficulty: "Hard",
  },
  {
    question: "What was the Silk Road?",
    options: ["A road made of silk", "Ancient trade routes", "A river in China", "A military campaign"],
    correctAnswer: 1,
    category: "History",
    difficulty: "Hard",
  },
  {
    question: "Who wrote 'The Prince', a political treatise?",
    options: ["Thomas More", "Machiavelli", "Voltaire", "Rousseau"],
    correctAnswer: 1,
    category: "History",
    difficulty: "Hard",
  },
  {
    question: "Which treaty ended World War I?",
    options: ["Treaty of Paris", "Treaty of Versailles", "Treaty of Westphalia", "Treaty of Vienna"],
    correctAnswer: 1,
    category: "History",
    difficulty: "Hard",
  },
  {
    question: "What was the Scramble for Africa?",
    options: [
      "African independence movements",
      "European colonization of Africa",
      "African trade routes",
      "African cultural exchange",
    ],
    correctAnswer: 1,
    category: "History",
    difficulty: "Hard",
  },
  {
    question: "Who was the founder of the Mongol Empire?",
    options: ["Kublai Khan", "Genghis Khan", "Tamerlane", "Attila the Hun"],
    correctAnswer: 1,
    category: "History",
    difficulty: "Hard",
  },

  // Academia - Easy (10 questions)
  {
    question: "What is the square root of 144?",
    options: ["10", "11", "12", "13"],
    correctAnswer: 2,
    category: "Academia",
    difficulty: "Easy",
  },
  {
    question: "Who wrote 'Romeo and Juliet'?",
    options: ["Charles Dickens", "William Shakespeare", "Jane Austen", "Mark Twain"],
    correctAnswer: 1,
    category: "Academia",
    difficulty: "Easy",
  },
  {
    question: "What is 7 × 8?",
    options: ["54", "56", "58", "60"],
    correctAnswer: 1,
    category: "Academia",
    difficulty: "Easy",
  },
  {
    question: "How many sides does a hexagon have?",
    options: ["5", "6", "7", "8"],
    correctAnswer: 1,
    category: "Academia",
    difficulty: "Easy",
  },
  {
    question: "What is the capital of Japan?",
    options: ["Seoul", "Beijing", "Tokyo", "Bangkok"],
    correctAnswer: 2,
    category: "Academia",
    difficulty: "Easy",
  },
  {
    question: "How many continents are there?",
    options: ["5", "6", "7", "8"],
    correctAnswer: 2,
    category: "Academia",
    difficulty: "Easy",
  },
  {
    question: "What is 25% of 200?",
    options: ["25", "50", "75", "100"],
    correctAnswer: 1,
    category: "Academia",
    difficulty: "Easy",
  },
  {
    question: "Who wrote 'The Odyssey'?",
    options: ["Virgil", "Homer", "Sophocles", "Aristotle"],
    correctAnswer: 1,
    category: "Academia",
    difficulty: "Easy",
  },
  {
    question: "What is the smallest prime number?",
    options: ["0", "1", "2", "3"],
    correctAnswer: 2,
    category: "Academia",
    difficulty: "Easy",
  },
  {
    question: "How many degrees are in a right angle?",
    options: ["45", "60", "90", "180"],
    correctAnswer: 2,
    category: "Academia",
    difficulty: "Easy",
  },

  // Academia - Intermediate (10 questions)
  {
    question: "What is the derivative of x²?",
    options: ["x", "2x", "x²", "2"],
    correctAnswer: 1,
    category: "Academia",
    difficulty: "Intermediate",
  },
  {
    question: "What is the quadratic formula?",
    options: [
      "x = -b ± √(b² - 4ac) / 2a",
      "x = b ± √(b² + 4ac) / 2a",
      "x = -b ± √(b² + 4ac) / a",
      "x = b ± √(b² - 4ac) / a",
    ],
    correctAnswer: 0,
    category: "Academia",
    difficulty: "Intermediate",
  },
  {
    question: "What is the value of π (pi) approximately?",
    options: ["2.14", "3.14", "4.14", "5.14"],
    correctAnswer: 1,
    category: "Academia",
    difficulty: "Intermediate",
  },
  {
    question: "Who wrote '1984'?",
    options: ["Aldous Huxley", "George Orwell", "Ray Bradbury", "H.G. Wells"],
    correctAnswer: 1,
    category: "Academia",
    difficulty: "Intermediate",
  },
  {
    question: "What is the Pythagorean theorem?",
    options: ["a + b = c", "a² + b² = c²", "a × b = c", "a² × b² = c²"],
    correctAnswer: 1,
    category: "Academia",
    difficulty: "Intermediate",
  },
  {
    question: "What is the sum of angles in a triangle?",
    options: ["90°", "180°", "270°", "360°"],
    correctAnswer: 1,
    category: "Academia",
    difficulty: "Intermediate",
  },
  {
    question: "Who painted 'The Starry Night'?",
    options: ["Pablo Picasso", "Vincent van Gogh", "Claude Monet", "Salvador Dalí"],
    correctAnswer: 1,
    category: "Academia",
    difficulty: "Intermediate",
  },
  {
    question: "What is the formula for the area of a circle?",
    options: ["πr", "πr²", "2πr", "πd"],
    correctAnswer: 1,
    category: "Academia",
    difficulty: "Intermediate",
  },
  {
    question: "What does the term 'renaissance' mean?",
    options: ["Rebirth", "Revolution", "Reform", "Renewal"],
    correctAnswer: 0,
    category: "Academia",
    difficulty: "Intermediate",
  },
  {
    question: "What is an isosceles triangle?",
    options: ["All sides equal", "Two sides equal", "No sides equal", "One right angle"],
    correctAnswer: 1,
    category: "Academia",
    difficulty: "Intermediate",
  },

  // Academia - Hard (10 questions)
  {
    question: "Who developed the theory of general relativity?",
    options: ["Isaac Newton", "Albert Einstein", "Niels Bohr", "Stephen Hawking"],
    correctAnswer: 1,
    category: "Academia",
    difficulty: "Hard",
  },
  {
    question: "What is the integral of 1/x?",
    options: ["ln|x| + C", "x² + C", "1/x² + C", "e^x + C"],
    correctAnswer: 0,
    category: "Academia",
    difficulty: "Hard",
  },
  {
    question: "What is Euler's identity?",
    options: ["e^(iπ) + 1 = 0", "e^(iπ) - 1 = 0", "e^(iπ) = 1", "e^(π) + i = 0"],
    correctAnswer: 0,
    category: "Academia",
    difficulty: "Hard",
  },
  {
    question: "Who wrote 'Critique of Pure Reason'?",
    options: ["Immanuel Kant", "Friedrich Nietzsche", "René Descartes", "John Locke"],
    correctAnswer: 0,
    category: "Academia",
    difficulty: "Hard",
  },
  {
    question: "What is the Riemann Hypothesis about?",
    options: ["Distribution of prime numbers", "Geometry of space", "Theory of relativity", "Quantum mechanics"],
    correctAnswer: 0,
    category: "Academia",
    difficulty: "Hard",
  },
  {
    question: "What is Gödel's Incompleteness Theorem?",
    options: [
      "Some mathematical truths cannot be proven",
      "All math is incomplete",
      "Mathematics is inconsistent",
      "Logic is flawed",
    ],
    correctAnswer: 0,
    category: "Academia",
    difficulty: "Hard",
  },
  {
    question: "What is the Hegelian dialectic?",
    options: ["Thesis, Antithesis, Synthesis", "Cause and Effect", "Trial and Error", "Question and Answer"],
    correctAnswer: 0,
    category: "Academia",
    difficulty: "Hard",
  },
  {
    question: "What is Fermat's Last Theorem?",
    options: [
      "No three positive integers satisfy a^n + b^n = c^n for n > 2",
      "All primes are odd",
      "π is irrational",
      "e is transcendental",
    ],
    correctAnswer: 0,
    category: "Academia",
    difficulty: "Hard",
  },
  {
    question: "Who developed set theory?",
    options: ["Georg Cantor", "Bertrand Russell", "David Hilbert", "Kurt Gödel"],
    correctAnswer: 0,
    category: "Academia",
    difficulty: "Hard",
  },
  {
    question: "What is the P vs NP problem?",
    options: [
      "A problem in computer science about complexity",
      "A physics theorem",
      "A mathematical proof",
      "A logic puzzle",
    ],
    correctAnswer: 0,
    category: "Academia",
    difficulty: "Hard",
  },

  // Engineering - Easy (10 questions)
  {
    question: "What is the unit of electrical resistance?",
    options: ["Volt", "Ampere", "Ohm", "Watt"],
    correctAnswer: 2,
    category: "Engineering",
    difficulty: "Easy",
  },
  {
    question: "What does DC stand for in electricity?",
    options: ["Direct Current", "Double Current", "Dynamic Current", "Dual Circuit"],
    correctAnswer: 0,
    category: "Engineering",
    difficulty: "Easy",
  },
  {
    question: "What tool is used to measure voltage?",
    options: ["Ammeter", "Voltmeter", "Ohmmeter", "Wattmeter"],
    correctAnswer: 1,
    category: "Engineering",
    difficulty: "Easy",
  },
  {
    question: "What is the primary function of a capacitor?",
    options: ["Resist current", "Store charge", "Amplify signal", "Generate power"],
    correctAnswer: 1,
    category: "Engineering",
    difficulty: "Easy",
  },
  {
    question: "What material is commonly used in electrical wiring?",
    options: ["Iron", "Copper", "Aluminum", "Gold"],
    correctAnswer: 1,
    category: "Engineering",
    difficulty: "Easy",
  },
  {
    question: "What does AC stand for in electricity?",
    options: ["Alternating Current", "Active Current", "Applied Current", "Automatic Current"],
    correctAnswer: 0,
    category: "Engineering",
    difficulty: "Easy",
  },
  {
    question: "What is the unit of power?",
    options: ["Joule", "Watt", "Volt", "Ampere"],
    correctAnswer: 1,
    category: "Engineering",
    difficulty: "Easy",
  },
  {
    question: "What is the main component of steel?",
    options: ["Aluminum", "Iron", "Copper", "Zinc"],
    correctAnswer: 1,
    category: "Engineering",
    difficulty: "Easy",
  },
  {
    question: "What is the purpose of a circuit breaker?",
    options: ["Increase voltage", "Protect from overload", "Store energy", "Amplify signal"],
    correctAnswer: 1,
    category: "Engineering",
    difficulty: "Easy",
  },
  {
    question: "What does LED stand for?",
    options: ["Light Emitting Diode", "Long Energy Device", "Low Emission Display", "Linear Electric Device"],
    correctAnswer: 0,
    category: "Engineering",
    difficulty: "Easy",
  },

  // Engineering - Intermediate (10 questions)
  {
    question: "What does CAD stand for in engineering?",
    options: [
      "Computer Aided Design",
      "Central Analysis Data",
      "Computer Advanced Development",
      "Central Aided Design",
    ],
    correctAnswer: 0,
    category: "Engineering",
    difficulty: "Intermediate",
  },
  {
    question: "What is Ohm's Law?",
    options: ["V = IR", "P = IV", "E = mc²", "F = ma"],
    correctAnswer: 0,
    category: "Engineering",
    difficulty: "Intermediate",
  },
  {
    question: "What is the modulus of elasticity a measure of?",
    options: ["Strength", "Stiffness", "Ductility", "Hardness"],
    correctAnswer: 1,
    category: "Engineering",
    difficulty: "Intermediate",
  },
  {
    question: "What is the purpose of a heat exchanger?",
    options: ["Generate heat", "Transfer heat", "Store heat", "Measure heat"],
    correctAnswer: 1,
    category: "Engineering",
    difficulty: "Intermediate",
  },
  {
    question: "What is the SI unit of frequency?",
    options: ["Hertz", "Watt", "Joule", "Newton"],
    correctAnswer: 0,
    category: "Engineering",
    difficulty: "Intermediate",
  },
  {
    question: "What is a cantilever beam?",
    options: ["A beam supported at both ends", "A beam fixed at one end", "A circular beam", "A flexible beam"],
    correctAnswer: 1,
    category: "Engineering",
    difficulty: "Intermediate",
  },
  {
    question: "What does FEA stand for in engineering?",
    options: [
      "Finite Element Analysis",
      "Fast Execution Algorithm",
      "Force Energy Application",
      "Function Element Assembly",
    ],
    correctAnswer: 0,
    category: "Engineering",
    difficulty: "Intermediate",
  },
  {
    question: "What is the difference between stress and strain?",
    options: [
      "Stress is force, strain is deformation",
      "Stress is deformation, strain is force",
      "They are the same",
      "Stress is internal, strain is external",
    ],
    correctAnswer: 0,
    category: "Engineering",
    difficulty: "Intermediate",
  },
  {
    question: "What is the purpose of a flywheel?",
    options: ["Store rotational energy", "Generate electricity", "Cool the engine", "Filter air"],
    correctAnswer: 0,
    category: "Engineering",
    difficulty: "Intermediate",
  },
  {
    question: "What is the Carnot cycle?",
    options: ["A mechanical cycle", "An ideal thermodynamic cycle", "An electrical cycle", "A chemical process"],
    correctAnswer: 1,
    category: "Engineering",
    difficulty: "Intermediate",
  },

  // Engineering - Hard (10 questions)
  {
    question: "What is the Mohs hardness of diamond?",
    options: ["8", "9", "10", "11"],
    correctAnswer: 2,
    category: "Engineering",
    difficulty: "Hard",
  },
  {
    question: "What is the Reynolds number used for?",
    options: ["Determine flow regime", "Measure temperature", "Calculate stress", "Find resistance"],
    correctAnswer: 0,
    category: "Engineering",
    difficulty: "Hard",
  },
  {
    question: "What is Poisson's ratio?",
    options: [
      "Ratio of lateral to axial strain",
      "Ratio of stress to strain",
      "Ratio of force to area",
      "Ratio of volume to mass",
    ],
    correctAnswer: 0,
    category: "Engineering",
    difficulty: "Hard",
  },
  {
    question: "What is the Biot-Savart law used for?",
    options: ["Calculate magnetic field", "Measure temperature", "Find resistance", "Determine flow rate"],
    correctAnswer: 0,
    category: "Engineering",
    difficulty: "Hard",
  },
  {
    question: "What is the critical path method in project management?",
    options: ["Longest sequence of dependent tasks", "Shortest route", "Most expensive path", "Easiest method"],
    correctAnswer: 0,
    category: "Engineering",
    difficulty: "Hard",
  },
  {
    question: "What is the Nyquist sampling theorem?",
    options: [
      "Sample at twice the highest frequency",
      "Sample at highest frequency",
      "Sample at lowest frequency",
      "Sample continuously",
    ],
    correctAnswer: 0,
    category: "Engineering",
    difficulty: "Hard",
  },
  {
    question: "What is the purpose of annealing in metallurgy?",
    options: ["Harden metal", "Soften metal and relieve stress", "Coat metal", "Polish metal"],
    correctAnswer: 1,
    category: "Engineering",
    difficulty: "Hard",
  },
  {
    question: "What is Bernoulli's principle?",
    options: [
      "Pressure decreases with increased velocity",
      "Pressure increases with velocity",
      "Temperature affects pressure",
      "Volume is constant",
    ],
    correctAnswer: 0,
    category: "Engineering",
    difficulty: "Hard",
  },
  {
    question: "What is the purpose of a PID controller?",
    options: ["Process control feedback", "Generate power", "Store data", "Filter signals"],
    correctAnswer: 0,
    category: "Engineering",
    difficulty: "Hard",
  },
  {
    question: "What is the Hall effect?",
    options: [
      "Voltage across conductor in magnetic field",
      "Resistance change with temperature",
      "Light emission from electrons",
      "Sound wave propagation",
    ],
    correctAnswer: 0,
    category: "Engineering",
    difficulty: "Hard",
  },

  // Law - Easy (10 questions)
  {
    question: "What is the supreme law of the United States?",
    options: ["Declaration of Independence", "Bill of Rights", "The Constitution", "The Amendments"],
    correctAnswer: 2,
    category: "Law",
    difficulty: "Easy",
  },
  {
    question: "How many branches are there in the US government?",
    options: ["2", "3", "4", "5"],
    correctAnswer: 1,
    category: "Law",
    difficulty: "Easy",
  },
  {
    question: "What is the highest court in the United States?",
    options: ["District Court", "Appeals Court", "Supreme Court", "Federal Court"],
    correctAnswer: 2,
    category: "Law",
    difficulty: "Easy",
  },
  {
    question: "What does the Fifth Amendment protect against?",
    options: ["Self-incrimination", "Unlawful search", "Cruel punishment", "Trial delay"],
    correctAnswer: 0,
    category: "Law",
    difficulty: "Easy",
  },
  {
    question: "What is a felony?",
    options: ["Minor crime", "Serious crime", "Traffic violation", "Civil dispute"],
    correctAnswer: 1,
    category: "Law",
    difficulty: "Easy",
  },
  {
    question: "What does 'pro bono' mean?",
    options: ["For the public good/free", "Against", "In favor of", "Professional"],
    correctAnswer: 0,
    category: "Law",
    difficulty: "Easy",
  },
  {
    question: "What is a misdemeanor?",
    options: ["Serious crime", "Minor crime", "Civil case", "Contract dispute"],
    correctAnswer: 1,
    category: "Law",
    difficulty: "Easy",
  },
  {
    question: "What does the First Amendment protect?",
    options: ["Right to bear arms", "Freedom of speech", "Right to vote", "Due process"],
    correctAnswer: 1,
    category: "Law",
    difficulty: "Easy",
  },
  {
    question: "What is a plaintiff?",
    options: ["Judge", "Person who sues", "Defendant", "Witness"],
    correctAnswer: 1,
    category: "Law",
    difficulty: "Easy",
  },
  {
    question: "What is bail?",
    options: ["Final verdict", "Money for release pending trial", "Type of punishment", "Court fee"],
    correctAnswer: 1,
    category: "Law",
    difficulty: "Easy",
  },

  // Law - Intermediate (10 questions)
  {
    question: "What does 'habeas corpus' mean?",
    options: ["You have the body", "Guilty mind", "The thing speaks for itself", "Let the buyer beware"],
    correctAnswer: 0,
    category: "Law",
    difficulty: "Intermediate",
  },
  {
    question: "What is the burden of proof in criminal cases?",
    options: ["Preponderance of evidence", "Beyond reasonable doubt", "Clear and convincing", "Probable cause"],
    correctAnswer: 1,
    category: "Law",
    difficulty: "Intermediate",
  },
  {
    question: "What is tort law?",
    options: ["Criminal law", "Civil wrongs and damages", "Contract law", "Property law"],
    correctAnswer: 1,
    category: "Law",
    difficulty: "Intermediate",
  },
  {
    question: "What does 'stare decisis' mean?",
    options: ["Stand by decided cases", "State the case", "Start proceedings", "Stop the trial"],
    correctAnswer: 0,
    category: "Law",
    difficulty: "Intermediate",
  },
  {
    question: "What is judicial review?",
    options: ["Reviewing judges", "Courts examining constitutionality of laws", "Jury deliberation", "Case review"],
    correctAnswer: 1,
    category: "Law",
    difficulty: "Intermediate",
  },
  {
    question: "What is a grand jury?",
    options: ["Trial jury", "Group determining if charges should be filed", "Supreme Court panel", "Appeals board"],
    correctAnswer: 1,
    category: "Law",
    difficulty: "Intermediate",
  },
  {
    question: "What does 'double jeopardy' prohibit?",
    options: ["Two trials", "Being tried twice for same offense", "Two punishments", "Two charges"],
    correctAnswer: 1,
    category: "Law",
    difficulty: "Intermediate",
  },
  {
    question: "What is civil law?",
    options: ["Criminal law", "Law between private parties", "Military law", "Constitutional law"],
    correctAnswer: 1,
    category: "Law",
    difficulty: "Intermediate",
  },
  {
    question: "What is an injunction?",
    options: ["Court order to do or not do something", "Fine", "Jail sentence", "Appeal"],
    correctAnswer: 0,
    category: "Law",
    difficulty: "Intermediate",
  },
  {
    question: "What is the Miranda warning?",
    options: ["Fire alarm", "Rights read to arrested persons", "Court summons", "Traffic citation"],
    correctAnswer: 1,
    category: "Law",
    difficulty: "Intermediate",
  },

  // Law - Hard (10 questions)
  {
    question: "In which case did the US Supreme Court establish judicial review?",
    options: ["Brown v. Board", "Marbury v. Madison", "Roe v. Wade", "Miranda v. Arizona"],
    correctAnswer: 1,
    category: "Law",
    difficulty: "Hard",
  },
  {
    question: "What is the rule against perpetuities?",
    options: [
      "Property law limiting future interests",
      "Criminal statute of limitations",
      "Contract expiration",
      "Trademark duration",
    ],
    correctAnswer: 0,
    category: "Law",
    difficulty: "Hard",
  },
  {
    question: "What is the difference between malum in se and malum prohibitum?",
    options: [
      "Wrong in itself vs. wrong because prohibited",
      "Federal vs. state crime",
      "Felony vs. misdemeanor",
      "Civil vs. criminal",
    ],
    correctAnswer: 0,
    category: "Law",
    difficulty: "Hard",
  },
  {
    question: "What is the Chevron deference?",
    options: [
      "Judicial deference to agency interpretation",
      "Presidential power",
      "Congressional privilege",
      "State sovereignty",
    ],
    correctAnswer: 0,
    category: "Law",
    difficulty: "Hard",
  },
  {
    question: "What is the doctrine of res ipsa loquitur?",
    options: ["The thing speaks for itself", "Let the buyer beware", "As you have done", "At first sight"],
    correctAnswer: 0,
    category: "Law",
    difficulty: "Hard",
  },
  {
    question: "What is qualified immunity?",
    options: [
      "Protection for public officials from liability",
      "Diplomatic immunity",
      "Witness protection",
      "Jury immunity",
    ],
    correctAnswer: 0,
    category: "Law",
    difficulty: "Hard",
  },
  {
    question: "What is the Dormant Commerce Clause?",
    options: [
      "Limits on state laws affecting interstate commerce",
      "Federal taxation power",
      "Presidential veto",
      "Judicial appointments",
    ],
    correctAnswer: 0,
    category: "Law",
    difficulty: "Hard",
  },
  {
    question: "What is forum non conveniens?",
    options: ["Dismissal for inconvenient forum", "Public forum", "Court calendar", "Jury selection"],
    correctAnswer: 0,
    category: "Law",
    difficulty: "Hard",
  },
  {
    question: "What is the Parol Evidence Rule?",
    options: [
      "Bars extrinsic evidence of prior agreements",
      "Hearsay exception",
      "Evidence authentication",
      "Witness credibility",
    ],
    correctAnswer: 0,
    category: "Law",
    difficulty: "Hard",
  },
  {
    question: "What is substantive due process?",
    options: ["Protection of fundamental rights", "Trial procedures", "Evidence rules", "Sentencing guidelines"],
    correctAnswer: 0,
    category: "Law",
    difficulty: "Hard",
  },

  // Economics - Easy (10 questions)
  {
    question: "What does GDP stand for?",
    options: [
      "General Domestic Product",
      "Gross Domestic Product",
      "General Development Price",
      "Gross Development Price",
    ],
    correctAnswer: 1,
    category: "Economics",
    difficulty: "Easy",
  },
  {
    question: "What is supply and demand?",
    options: ["Relationship between availability and desire", "Taxation system", "Banking method", "Trade agreement"],
    correctAnswer: 0,
    category: "Economics",
    difficulty: "Easy",
  },
  {
    question: "What is a monopoly?",
    options: ["Many sellers", "One seller controls market", "Government control", "Free market"],
    correctAnswer: 1,
    category: "Economics",
    difficulty: "Easy",
  },
  {
    question: "What is opportunity cost?",
    options: ["Money spent", "Value of next best alternative", "Production cost", "Market price"],
    correctAnswer: 1,
    category: "Economics",
    difficulty: "Easy",
  },
  {
    question: "What is currency?",
    options: ["System of money", "Bank account", "Credit card", "Stock"],
    correctAnswer: 0,
    category: "Economics",
    difficulty: "Easy",
  },
  {
    question: "What is a recession?",
    options: ["Economic growth", "Economic decline", "Stable economy", "High employment"],
    correctAnswer: 1,
    category: "Economics",
    difficulty: "Easy",
  },
  {
    question: "What is interest?",
    options: ["Cost of borrowing money", "Type of tax", "Market share", "Business profit"],
    correctAnswer: 0,
    category: "Economics",
    difficulty: "Easy",
  },
  {
    question: "What is a stock?",
    options: ["Loan", "Ownership share in company", "Bond", "Commodity"],
    correctAnswer: 1,
    category: "Economics",
    difficulty: "Easy",
  },
  {
    question: "What is unemployment?",
    options: [
      "People working part-time",
      "People actively seeking work but unable to find it",
      "Retired people",
      "Students",
    ],
    correctAnswer: 1,
    category: "Economics",
    difficulty: "Easy",
  },
  {
    question: "What is a budget?",
    options: ["Financial plan", "Bank account", "Credit score", "Investment portfolio"],
    correctAnswer: 0,
    category: "Economics",
    difficulty: "Easy",
  },

  // Economics - Intermediate (10 questions)
  {
    question: "What is inflation?",
    options: ["Rising prices over time", "Falling prices over time", "Stable prices", "Currency exchange"],
    correctAnswer: 0,
    category: "Economics",
    difficulty: "Intermediate",
  },
  {
    question: "What is fiscal policy?",
    options: ["Government spending and taxation", "Interest rates", "Currency exchange", "Trade agreements"],
    correctAnswer: 0,
    category: "Economics",
    difficulty: "Intermediate",
  },
  {
    question: "What is monetary policy?",
    options: ["Government budget", "Central bank control of money supply", "Tax collection", "Trade regulation"],
    correctAnswer: 1,
    category: "Economics",
    difficulty: "Intermediate",
  },
  {
    question: "What is the Federal Reserve?",
    options: ["Tax agency", "Central bank of the US", "Treasury department", "Congressional committee"],
    correctAnswer: 1,
    category: "Economics",
    difficulty: "Intermediate",
  },
  {
    question: "What is elasticity of demand?",
    options: [
      "Responsiveness of quantity demanded to price changes",
      "Total demand",
      "Market size",
      "Production capacity",
    ],
    correctAnswer: 0,
    category: "Economics",
    difficulty: "Intermediate",
  },
  {
    question: "What is comparative advantage?",
    options: ["Being best at everything", "Lower opportunity cost in production", "Largest economy", "Most resources"],
    correctAnswer: 1,
    category: "Economics",
    difficulty: "Intermediate",
  },
  {
    question: "What is marginal utility?",
    options: ["Total satisfaction", "Additional satisfaction from one more unit", "Average utility", "Maximum utility"],
    correctAnswer: 1,
    category: "Economics",
    difficulty: "Intermediate",
  },
  {
    question: "What is a trade deficit?",
    options: ["Imports exceed exports", "Exports exceed imports", "Balanced trade", "No trade"],
    correctAnswer: 0,
    category: "Economics",
    difficulty: "Intermediate",
  },
  {
    question: "What is aggregate demand?",
    options: ["Individual demand", "Total demand in economy", "Business demand", "Government demand"],
    correctAnswer: 1,
    category: "Economics",
    difficulty: "Intermediate",
  },
  {
    question: "What is a progressive tax?",
    options: ["Tax rate increases with income", "Fixed tax rate", "Tax on profits", "Sales tax"],
    correctAnswer: 0,
    category: "Economics",
    difficulty: "Intermediate",
  },

  // Economics - Hard (10 questions)
  {
    question: "Who wrote 'The Wealth of Nations'?",
    options: ["Karl Marx", "John Maynard Keynes", "Adam Smith", "Milton Friedman"],
    correctAnswer: 2,
    category: "Economics",
    difficulty: "Hard",
  },
  {
    question: "What is the Phillips Curve?",
    options: ["Relationship between inflation and unemployment", "Supply curve", "Demand curve", "Growth trajectory"],
    correctAnswer: 0,
    category: "Economics",
    difficulty: "Hard",
  },
  {
    question: "What is the Laffer Curve?",
    options: [
      "Relationship between tax rates and revenue",
      "Production possibility frontier",
      "Demand curve",
      "Growth model",
    ],
    correctAnswer: 0,
    category: "Economics",
    difficulty: "Hard",
  },
  {
    question: "What is rational expectations theory?",
    options: [
      "People make predictions using all available information",
      "People are irrational",
      "Markets are random",
      "Emotions drive decisions",
    ],
    correctAnswer: 0,
    category: "Economics",
    difficulty: "Hard",
  },
  {
    question: "What is the Solow growth model?",
    options: ["Economic growth from capital and labor", "Inflation model", "Trade theory", "Tax policy"],
    correctAnswer: 0,
    category: "Economics",
    difficulty: "Hard",
  },
  {
    question: "What is the Coase theorem?",
    options: [
      "If transaction costs are low, bargaining leads to efficiency",
      "Government intervention is necessary",
      "Markets always fail",
      "Monopolies are efficient",
    ],
    correctAnswer: 0,
    category: "Economics",
    difficulty: "Hard",
  },
  {
    question: "What is game theory in economics?",
    options: ["Study of strategic decision making", "Gambling mathematics", "Sport economics", "Market timing"],
    correctAnswer: 0,
    category: "Economics",
    difficulty: "Hard",
  },
  {
    question: "What is the Ricardian equivalence?",
    options: [
      "Debt and taxes have equivalent effects",
      "International trade theory",
      "Currency equivalence",
      "Price parity",
    ],
    correctAnswer: 0,
    category: "Economics",
    difficulty: "Hard",
  },
  {
    question: "What is asymmetric information?",
    options: [
      "One party has more information than another",
      "Equal information",
      "No information",
      "Public information",
    ],
    correctAnswer: 0,
    category: "Economics",
    difficulty: "Hard",
  },
  {
    question: "What is the efficient market hypothesis?",
    options: [
      "Asset prices reflect all available information",
      "Markets are inefficient",
      "Prices are random",
      "Insider trading works",
    ],
    correctAnswer: 0,
    category: "Economics",
    difficulty: "Hard",
  },

  // General - Easy (10 questions)
  {
    question: "What is the capital of France?",
    options: ["London", "Berlin", "Paris", "Madrid"],
    correctAnswer: 2,
    category: "General",
    difficulty: "Easy",
  },
  {
    question: "Which planet is known as the Red Planet?",
    options: ["Venus", "Mars", "Jupiter", "Saturn"],
    correctAnswer: 1,
    category: "General",
    difficulty: "Easy",
  },
  {
    question: "How many days are in a leap year?",
    options: ["364", "365", "366", "367"],
    correctAnswer: 2,
    category: "General",
    difficulty: "Easy",
  },
  {
    question: "What is the largest mammal in the world?",
    options: ["Elephant", "Blue Whale", "Giraffe", "Polar Bear"],
    correctAnswer: 1,
    category: "General",
    difficulty: "Easy",
  },
  {
    question: "How many colors are in a rainbow?",
    options: ["5", "6", "7", "8"],
    correctAnswer: 2,
    category: "General",
    difficulty: "Easy",
  },
  {
    question: "What is the tallest mountain in the world?",
    options: ["K2", "Mount Everest", "Kilimanjaro", "Mont Blanc"],
    correctAnswer: 1,
    category: "General",
    difficulty: "Easy",
  },
  {
    question: "Which ocean is the largest?",
    options: ["Atlantic", "Indian", "Arctic", "Pacific"],
    correctAnswer: 3,
    category: "General",
    difficulty: "Easy",
  },
  {
    question: "How many continents are there?",
    options: ["5", "6", "7", "8"],
    correctAnswer: 2,
    category: "General",
    difficulty: "Easy",
  },
  {
    question: "What is the capital of Australia?",
    options: ["Sydney", "Melbourne", "Canberra", "Perth"],
    correctAnswer: 2,
    category: "General",
    difficulty: "Easy",
  },
  {
    question: "How many sides does a triangle have?",
    options: ["2", "3", "4", "5"],
    correctAnswer: 1,
    category: "General",
    difficulty: "Easy",
  },

  // General - Intermediate (10 questions)
  {
    question: "What is the largest ocean on Earth?",
    options: ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"],
    correctAnswer: 3,
    category: "General",
    difficulty: "Intermediate",
  },
  {
    question: "Who painted the Mona Lisa?",
    options: ["Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso", "Claude Monet"],
    correctAnswer: 1,
    category: "General",
    difficulty: "Intermediate",
  },
  {
    question: "What is the longest river in the world?",
    options: ["Amazon", "Nile", "Mississippi", "Yangtze"],
    correctAnswer: 1,
    category: "General",
    difficulty: "Intermediate",
  },
  {
    question: "In which country is the Great Barrier Reef located?",
    options: ["Brazil", "Australia", "Indonesia", "Philippines"],
    correctAnswer: 1,
    category: "General",
    difficulty: "Intermediate",
  },
  {
    question: "What is the smallest country in the world?",
    options: ["Monaco", "Vatican City", "San Marino", "Liechtenstein"],
    correctAnswer: 1,
    category: "General",
    difficulty: "Intermediate",
  },
  {
    question: "How many time zones does Russia have?",
    options: ["7", "9", "11", "13"],
    correctAnswer: 2,
    category: "General",
    difficulty: "Intermediate",
  },
  {
    question: "What is the currency of Japan?",
    options: ["Yuan", "Won", "Yen", "Ringgit"],
    correctAnswer: 2,
    category: "General",
    difficulty: "Intermediate",
  },
  {
    question: "Which element has the chemical symbol 'Fe'?",
    options: ["Iron", "Fluorine", "Fermium", "Francium"],
    correctAnswer: 0,
    category: "General",
    difficulty: "Intermediate",
  },
  {
    question: "What year did the internet become available to the public?",
    options: ["1981", "1991", "2001", "1971"],
    correctAnswer: 1,
    category: "General",
    difficulty: "Intermediate",
  },
  {
    question: "What is the most spoken language in the world?",
    options: ["English", "Spanish", "Mandarin Chinese", "Hindi"],
    correctAnswer: 2,
    category: "General",
    difficulty: "Intermediate",
  },

  // General - Hard (10 questions)
  {
    question: "What is the smallest prime number?",
    options: ["0", "1", "2", "3"],
    correctAnswer: 2,
    category: "General",
    difficulty: "Hard",
  },
  {
    question: "Which country has the most UNESCO World Heritage Sites?",
    options: ["France", "China", "Italy", "Spain"],
    correctAnswer: 2,
    category: "General",
    difficulty: "Hard",
  },
  {
    question: "What is the rarest blood type?",
    options: ["AB positive", "O negative", "AB negative", "B negative"],
    correctAnswer: 2,
    category: "General",
    difficulty: "Hard",
  },
  {
    question: "What is the capital of Mongolia?",
    options: ["Ulaanbaatar", "Astana", "Bishkek", "Dushanbe"],
    correctAnswer: 0,
    category: "General",
    difficulty: "Hard",
  },
  {
    question: "Which planet has the most moons?",
    options: ["Jupiter", "Saturn", "Uranus", "Neptune"],
    correctAnswer: 1,
    category: "General",
    difficulty: "Hard",
  },
  {
    question: "What is the deepest point in Earth's oceans?",
    options: ["Java Trench", "Puerto Rico Trench", "Mariana Trench", "Tonga Trench"],
    correctAnswer: 2,
    category: "General",
    difficulty: "Hard",
  },
  {
    question: "What is the oldest continuously inhabited city in the world?",
    options: ["Athens", "Rome", "Damascus", "Jerusalem"],
    correctAnswer: 2,
    category: "General",
    difficulty: "Hard",
  },
  {
    question: "How many bones does a shark have?",
    options: ["0", "50", "100", "200"],
    correctAnswer: 0,
    category: "General",
    difficulty: "Hard",
  },
  {
    question: "What is the largest desert in the world?",
    options: ["Sahara", "Arabian", "Gobi", "Antarctic"],
    correctAnswer: 3,
    category: "General",
    difficulty: "Hard",
  },
  {
    question: "Which element is the most abundant in the universe?",
    options: ["Oxygen", "Carbon", "Hydrogen", "Helium"],
    correctAnswer: 2,
    category: "General",
    difficulty: "Hard",
  },

  // Politics - Easy (10 questions)
  {
    question: "How many branches are there in the US government?",
    options: ["2", "3", "4", "5"],
    correctAnswer: 1,
    category: "Politics",
    difficulty: "Easy",
  },
  {
    question: "Who is the current head of the United Nations?",
    options: ["President", "Prime Minister", "Secretary-General", "Chancellor"],
    correctAnswer: 2,
    category: "Politics",
    difficulty: "Easy",
  },
  {
    question: "What does UN stand for?",
    options: ["Universal Nations", "United Nations", "Union of Nations", "Unified Nations"],
    correctAnswer: 1,
    category: "Politics",
    difficulty: "Easy",
  },
  {
    question: "How many stars are on the US flag?",
    options: ["48", "50", "51", "52"],
    correctAnswer: 1,
    category: "Politics",
    difficulty: "Easy",
  },
  {
    question: "What is the capital of the United States?",
    options: ["New York", "Washington D.C.", "Los Angeles", "Chicago"],
    correctAnswer: 1,
    category: "Politics",
    difficulty: "Easy",
  },
  {
    question: "Who has the power to veto bills in the US?",
    options: ["Speaker of the House", "President", "Supreme Court", "Senate"],
    correctAnswer: 1,
    category: "Politics",
    difficulty: "Easy",
  },
  {
    question: "What is the minimum voting age in the US?",
    options: ["16", "18", "21", "25"],
    correctAnswer: 1,
    category: "Politics",
    difficulty: "Easy",
  },
  {
    question: "How many US Senators are there?",
    options: ["50", "100", "435", "538"],
    correctAnswer: 1,
    category: "Politics",
    difficulty: "Easy",
  },
  {
    question: "What is the term for a country ruled by a king or queen?",
    options: ["Democracy", "Republic", "Monarchy", "Oligarchy"],
    correctAnswer: 2,
    category: "Politics",
    difficulty: "Easy",
  },
  {
    question: "What is democracy?",
    options: ["Rule by one person", "Rule by the people", "Rule by military", "Rule by clergy"],
    correctAnswer: 1,
    category: "Politics",
    difficulty: "Easy",
  },

  // Politics - Intermediate (10 questions)
  {
    question: "What is the term length for a US Senator?",
    options: ["2 years", "4 years", "6 years", "8 years"],
    correctAnswer: 2,
    category: "Politics",
    difficulty: "Intermediate",
  },
  {
    question: "What is the Electoral College?",
    options: ["Educational institution", "System for electing president", "Legislative body", "Political party"],
    correctAnswer: 1,
    category: "Politics",
    difficulty: "Intermediate",
  },
  {
    question: "How many justices are on the US Supreme Court?",
    options: ["7", "9", "11", "13"],
    correctAnswer: 1,
    category: "Politics",
    difficulty: "Intermediate",
  },
  {
    question: "What is a filibuster?",
    options: ["Extended speech to delay vote", "Type of election", "Court ruling", "Presidential order"],
    correctAnswer: 0,
    category: "Politics",
    difficulty: "Intermediate",
  },
  {
    question: "What does NATO stand for?",
    options: [
      "National Atlantic Treaty Organization",
      "North Atlantic Treaty Organization",
      "New Atlantic Trade Organization",
      "Northern Alliance Treaty Organization",
    ],
    correctAnswer: 1,
    category: "Politics",
    difficulty: "Intermediate",
  },
  {
    question: "What is a bicameral legislature?",
    options: [
      "One legislative chamber",
      "Two legislative chambers",
      "Three legislative chambers",
      "No legislative chambers",
    ],
    correctAnswer: 1,
    category: "Politics",
    difficulty: "Intermediate",
  },
  {
    question: "What is the primary function of the judicial branch?",
    options: ["Make laws", "Enforce laws", "Interpret laws", "Propose laws"],
    correctAnswer: 2,
    category: "Politics",
    difficulty: "Intermediate",
  },
  {
    question: "What is gerrymandering?",
    options: ["Fair redistricting", "Manipulating district boundaries", "Electoral reform", "Campaign finance"],
    correctAnswer: 1,
    category: "Politics",
    difficulty: "Intermediate",
  },
  {
    question: "What is a parliamentary system?",
    options: ["Executive chosen by legislature", "Directly elected president", "Military rule", "Hereditary monarchy"],
    correctAnswer: 0,
    category: "Politics",
    difficulty: "Intermediate",
  },
  {
    question: "What is the War Powers Act?",
    options: ["Declares war", "Limits presidential military action", "Funds military", "Creates treaties"],
    correctAnswer: 1,
    category: "Politics",
    difficulty: "Intermediate",
  },

  // Politics - Hard (10 questions)
  {
    question: "Which amendment granted women the right to vote in the US?",
    options: ["15th Amendment", "19th Amendment", "21st Amendment", "24th Amendment"],
    correctAnswer: 1,
    category: "Politics",
    difficulty: "Hard",
  },
  {
    question: "What is the Westphalian sovereignty?",
    options: ["State sovereignty within borders", "International law", "Colonial system", "Trade agreement"],
    correctAnswer: 0,
    category: "Politics",
    difficulty: "Hard",
  },
  {
    question: "What is the Iron Triangle in politics?",
    options: [
      "Relationship between Congress, bureaucracy, and interest groups",
      "Military alliance",
      "Trade bloc",
      "Election system",
    ],
    correctAnswer: 0,
    category: "Politics",
    difficulty: "Hard",
  },
  {
    question: "What is the median voter theorem?",
    options: ["Candidates converge to center", "Extremism wins", "Voter turnout theory", "Campaign finance model"],
    correctAnswer: 0,
    category: "Politics",
    difficulty: "Hard",
  },
  {
    question: "What is a unitary state?",
    options: ["Federal system", "Central government has all power", "Confederacy", "City-state"],
    correctAnswer: 1,
    category: "Politics",
    difficulty: "Hard",
  },
  {
    question: "What is the Duverger's law?",
    options: [
      "Plurality systems lead to two parties",
      "Proportional representation required",
      "Term limits necessary",
      "Campaign finance limits",
    ],
    correctAnswer: 0,
    category: "Politics",
    difficulty: "Hard",
  },
  {
    question: "What is soft power in international relations?",
    options: [
      "Military force",
      "Influence through attraction and persuasion",
      "Economic sanctions",
      "Trade agreements",
    ],
    correctAnswer: 1,
    category: "Politics",
    difficulty: "Hard",
  },
  {
    question: "What is the principal-agent problem in politics?",
    options: ["Difficulty monitoring representatives", "Election fraud", "Campaign finance", "Term limits"],
    correctAnswer: 0,
    category: "Politics",
    difficulty: "Hard",
  },
  {
    question: "What is constructivism in international relations?",
    options: [
      "Social constructs shape state behavior",
      "Military power determines outcomes",
      "Economic interests drive policy",
      "Geography determines politics",
    ],
    correctAnswer: 0,
    category: "Politics",
    difficulty: "Hard",
  },
  {
    question: "What is the veil of ignorance in political philosophy?",
    options: [
      "John Rawls' thought experiment for justice",
      "Information censorship",
      "Voter ignorance",
      "Campaign strategy",
    ],
    correctAnswer: 0,
    category: "Politics",
    difficulty: "Hard",
  },
]

function shuffleArray<T>(array: T[]): T[] {
  const shuffled = [...array]
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]]
  }
  return shuffled
}

export function getQuestionsByTypeAndLevel(type: QuizType, level: DifficultyLevel): Question[] {
  const filtered = QUIZ_DATA.filter((q) => q.category === type && q.difficulty === level)

  // Shuffle the questions to ensure randomization
  const shuffled = shuffleArray(filtered)

  // Return all available questions (up to 10)
  return shuffled.slice(0, Math.min(10, shuffled.length))
}
